<?php
/**
 * Title: Complete books catalog
 * Slug: gratia-gratis/books-catalog
 * Categories: gratia-gratis, featured
 * Description: Published and forthcoming books with a translation call to action.
 */
?>
<!-- wp:group {"metadata":{"name":"Complete books catalog"},"align":"full","className":"gg-books-catalog","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|40","bottom":"var:preset|spacing|60","left":"var:preset|spacing|40"}}},"backgroundColor":"parchment","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull gg-books-catalog has-parchment-background-color has-background" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--40)">
	<!-- wp:group {"align":"wide","className":"gg-books-group","layout":{"type":"constrained"}} -->
	<div class="wp-block-group alignwide gg-books-group">
		<!-- wp:group {"className":"gg-books-group-heading","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} -->
		<div class="wp-block-group gg-books-group-heading"><!-- wp:heading {"fontSize":"x-large"} --><h2 class="wp-block-heading has-x-large-font-size">Published</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"gg-eyebrow"} --><p class="gg-eyebrow">Available now / 03</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->

		<!-- wp:columns {"className":"gg-book-grid"} -->
		<div class="wp-block-columns gg-book-grid">
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","href":"https://www.amazon.it/dp/B0BLT3JZCD","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><a href="https://www.amazon.it/dp/B0BLT3JZCD"><img src="https://www.gratia.gratis/wp-content/uploads/2024/10/71sWk7J32pL._SL1500_.jpg" alt="Cover of Un Solenne Avvertimento"/></a></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size"><a href="https://www.amazon.it/dp/B0BLT3JZCD">Un Solenne Avvertimento</a></h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">Thomas Taylor</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta"><a href="https://www.amazon.it/dp/B0BLT3JZCD">Amazon ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","href":"https://solideogloriaedizioni.com/prodotto/dio-e-eterno-dr-william-lane-craig/","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-eterno-dr-william-lane-craig/"><img src="https://www.gratia.gratis/wp-content/uploads/2024/10/cop-Dio-e-eterno.png.webp" alt="Cover of Dio è Eterno"/></a></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-eterno-dr-william-lane-craig/">Dio è Eterno</a></h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">William Lane Craig</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-eterno-dr-william-lane-craig/">Publisher ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","href":"https://www.amazon.it/dp/B0CX97WCC8","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><a href="https://www.amazon.it/dp/B0CX97WCC8"><img src="https://www.gratia.gratis/wp-content/uploads/2024/10/61G5eqbv14L._SL1499_.jpg" alt="Cover of L’Eredità degli Affamati"/></a></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size"><a href="https://www.amazon.it/dp/B0CX97WCC8">L’Eredità degli Affamati</a></h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">Zane C. Hodges</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta"><a href="https://www.amazon.it/dp/B0CX97WCC8">Amazon ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		</div>
		<!-- /wp:columns -->
	</div>
	<!-- /wp:group -->

	<!-- wp:group {"align":"wide","className":"gg-books-group","style":{"spacing":{"margin":{"top":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
	<div class="wp-block-group alignwide gg-books-group" style="margin-top:var(--wp--preset--spacing--70)">
		<!-- wp:group {"className":"gg-books-group-heading","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} -->
		<div class="wp-block-group gg-books-group-heading"><!-- wp:heading {"fontSize":"x-large"} --><h2 class="wp-block-heading has-x-large-font-size">Coming soon</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"gg-eyebrow"} --><p class="gg-eyebrow">In translation / 03</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->

		<!-- wp:columns {"className":"gg-book-grid"} -->
		<div class="wp-block-columns gg-book-grid">
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><img src="https://gratia.gratis/wp-content/uploads/2024/10/71-8lcsto3L._SL1360_-683x1024.jpg" alt="Cover of Grace by Lewis Sperry Chafer"/></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size">Grace</h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">Lewis Sperry Chafer</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">In translation</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","href":"https://solideogloriaedizioni.com/prodotto/dio-e-spirito-dr-william-craig/","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-spirito-dr-william-craig/"><img src="https://www.gratia.gratis/wp-content/uploads/2024/10/cop-Dio-e-Spirito-scaled.jpg-1024x1007.webp" alt="Cover of Dio è Spirito"/></a></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-spirito-dr-william-craig/">Dio è Spirito</a></h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">William Lane Craig</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-spirito-dr-william-craig/">Preview ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
			<!-- wp:column {"className":"gg-book-card"} --><div class="wp-block-column gg-book-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","href":"https://solideogloriaedizioni.com/prodotto/dio-e-ovunque-dr-william-lane-craig/","className":"gg-book-cover"} --><figure class="wp-block-image size-large gg-book-cover"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-ovunque-dr-william-lane-craig/"><img src="https://www.gratia.gratis/wp-content/uploads/2024/10/Libro-Dio-e-Ovunque.png.webp" alt="Cover of Dio è Ovunque"/></a></figure><!-- /wp:image --><!-- wp:heading {"level":3,"className":"gg-book-title","fontSize":"large"} --><h3 class="wp-block-heading gg-book-title has-large-font-size"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-ovunque-dr-william-lane-craig/">Dio è Ovunque</a></h3><!-- /wp:heading --><!-- wp:group {"className":"gg-book-info","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group gg-book-info"><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta">William Lane Craig</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"gg-meta"} --><p class="gg-meta"><a href="https://solideogloriaedizioni.com/prodotto/dio-e-ovunque-dr-william-lane-craig/">Preview ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		</div>
		<!-- /wp:columns -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Book suggestion"},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|40","bottom":"var:preset|spacing|60","left":"var:preset|spacing|40"}}},"backgroundColor":"gold","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-gold-background-color has-background" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--40)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column {"width":"28%"} --><div class="wp-block-column" style="flex-basis:28%"><!-- wp:paragraph {"className":"gg-eyebrow"} --><p class="gg-eyebrow">Suggest a title</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"width":"50%"} --><div class="wp-block-column" style="flex-basis:50%"><!-- wp:heading {"fontSize":"x-large"} --><h2 class="wp-block-heading has-x-large-font-size">What should we translate next?</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Our pipeline is never empty, but we welcome suggestions for sound, grace-centred books that are not yet available in Italian.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/contact-us/">Send a suggestion →</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --><!-- wp:column {"width":"22%"} --><div class="wp-block-column" style="flex-basis:22%"><!-- wp:paragraph {"className":"gg-eyebrow"} --><p class="gg-eyebrow">Join the team</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Translators, proofreaders, designers, and publishing partners are always welcome.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->
