# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

engdb:
  type: mariadb:10.4
  disk: 512

itadb:
  type: mariadb:10.4
  disk: 512

redis:
  type: redis:5.0

es:
  type: elasticsearch:7.2
  disk: 256
